### ISSUE TITLE
The package is too opinionated, it can be better!

### ISSUE THREAD

**Issue by cloud-walker** [modosc/react-responsive-redux#1]
First of all, good job for the hard work, but for the greater good, I have to open this issue:

If you aim to solve the SSR + Device width issue, why is redux a thing?

This way you force all the user to use redux just for use your package, which is not obvious.

Furthermore your solution is dependent from `react-responsive`, why that? It could be more powerful and adoptable if it could solve the same issue for `react-media` or `react-sizeme` to name a few!

**Comment by modosc** [comment]
`redux` is the only way i've used to pass global state around to arbitrary components. i'd hope the name would make it clear that `redux` was a part of this.

if `react-media` and `react-sizeme` work in a similar way to `react-responsive` i'd welcome a pr to allow users to specify which wrapper component they want to use. for now this was just a repackaging of code i already used in response to an [ongoing conversation](https://github.com/contra/react-responsive/issues/42).

**Comment by modosc** [comment]
actually it occurs to me this could be done using react context, i'll keep this open and think about it.

**Comment by cloud-walker** [comment]
Yep you could this throught react context via hoc!

And I still think you could extract the user-agent logic too, to remove the react-responsive binding too

**Comment by modosc** [comment]
i don't see this changing any time soon so i'm going to close this out.
