### ISSUE TITLE
React.Fragment support for component prop

### ISSUE THREAD

**Issue by itsnorbertkalacska** [modosc/react-responsive-redux#10]
Hi there!

First of all, thank you so much for your work!

We started to use `react-responsive-redux` in our project and we need to render the `children` without any wrapping component. Right now the default wrapping component is a `div` (https://github.com/modosc/react-responsive-redux/blob/master/src/components.js#L34).

I passed `React.Fragment` as a prop like this:
```
<PhoneScreen component={React.Fragment}>...</PhoneScreen>

<DesktopScreen component={React.Fragment}>...</DesktopScreen>
```

However if I do this then there's a `console.error`:
```
Warning: Failed prop type: Invalid prop `component` supplied to `MediaQueryWrapper`.
```

Could we tackle this issue? Or am I missing something and tried to implement this wrong?

If you want to tackle this let me know if I can help.

Have a great day and thanks in advance!

**Comment by modosc** [comment]
thanks for the report - feel free to try and fix it, but i think the issue is related to #9 which isn't fixable on this end.

**Comment by modosc** [comment]
done, 0.9.0 is published to npm

**Comment by itsnorbertkalacska** [comment]
@modosc thank you!
