### ISSUE TITLE
Cannot read property 'fakeWidth' of undefined

### ISSUE THREAD

**Issue by kunal-arora** [modosc/react-responsive-redux#2]
`TypeError: Cannot read property 'fakeWidth' of undefined
    at Function.mapToProps (/var/www/html/ustraa_v2.1/node_modules/react-responsive-redux/lib/components.js:62:50)
    at mapToPropsProxy (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:92)
    at Function.detectFactoryAndVerify (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/connect/wrapMapToProps.js:63:19)
    at mapToPropsProxy (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:46)
    at handleFirstCall (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/connect/selectorFactory.js:37:18)
    at pureFinalPropsSelector (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/connect/selectorFactory.js:85:81)
    at Object.runComponentSelector [as run] (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/components/connectAdvanced.js:43:25)
    at Connect.initSelector (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/components/connectAdvanced.js:195:23)
    at new Connect (/var/www/html/ustraa_v2.1/node_modules/react-redux/lib/components/connectAdvanced.js:136:15)
    at /var/www/html/ustraa_v2.1/node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
`

This is what comes up on my terminal when I use MobileScreen, DesktopScreen in my components. I can see that the states are being set using Redux dev Tools. I am using ssr in my application, You can check the code [here](https://github.com/gitserverhu/ustraa_v2_react/blob/features/mobile-detect/v1.0/app/serverEntry.js)

[Update]
I was doing some digging and seemed to be a problem with the first render. Still no Idea what am I doing wrong.

**Comment by modosc** [comment]
i think it's because you're using https://github.com/gajus/redux-immutable - the `state` that's passed in to `mapStateToProps` is a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instead of a plain js object. 

i think it's an easy change to support this, let me check.

**Comment by modosc** [comment]
not as easy as it seemed - i built a [branch](https://github.com/modosc/react-responsive-redux/tree/immutable) which should handle this situation but it still blows up in your code. not really sure how to continue on from here - i haven't found any common patterns for writing redux code that works with and without immutable.js

**Comment by kunal-arora** [comment]
@modosc  thanks for looking into it. It seems like the best way would to use HOC.

**Comment by kunal-arora** [comment]
I knew that it something to do with immutable , so i added two lines in your components.js 
`state = JSON.stringify(state);`
`state = JSON.parse(state);` 
before 
`return _extends({ fakeWidth: state.responsive.fakeWidth }, props);`

**Comment by Jinnified** [comment]
i am having the same issue, but i am not using immutable, just plan old javascript object. But I am using nextjs for universal rendering, I plugged in the code for generate device detection and getting the store back on my redux store tree as per doc. 

1. getting the device type and populate it on the store tree. (I can see the data gets in the redux dev tool for the initial rendering)
```
static async getInitialProps({ store, req }) {
    let i18Decorated = {};
    const mobileDetect = mobileParser(req);
    store.dispatch(setMobileDetect(mobileDetect));
    if (req) {
      Helmet.renderStatic();
      if (!process.browser) {
        i18Decorated = i18n.getInitialProps(req, ['Guest', 'common']);
      }
    }
    return { ...i18Decorated, title: 'hello' };
  }
```

2. for the rendering part

```
render() {
    const { t, title } = this.props;
    return (
      <Layout>
        <div>{t('welcomeTitle')}</div>
        <p>{t('welcomeMsg')}</p>
        <DesktopScreen>
          <Skyscrapper primary>Desktop specific content</Skyscrapper>
        </DesktopScreen>
      </Layout>
    );
  }
}
```


The error i got is something like this: 
> TypeError: Cannot read property 'fakeWidth' of undefined at Function.mapToProps

**Comment by modosc** [comment]
i initially tried [supporting Maps](https://github.com/modosc/react-responsive-redux/commit/f5896d97c9ec26441b70c717f3f410da63506f9c) - that worked fine in my codebase but didn't work in @kunal-arora 's.

i'm totally open to a pr for this - [this page](https://redux.js.org/docs/recipes/UsingImmutableJS.html) has some suggestions for how to make it work. i just don't have the time to debug it on my own since i'm not currently using a codebase that has this setup.

**Comment by modosc** [comment]
@Jinnified also if you can publish a small test case that would be helpful?

**Comment by kunal-arora** [comment]
Sorry for such a late reply, Nothing worked for me using so I just ended up dispatching width using `store.dispatch(setMobileDetect(mobileDetect))` and then using the width obtained in Mediaquery tags of react-responsive. Though all this results in lag in render and no ssr :-1:  :(

**Comment by socean2016** [comment]
Could you give us a demo about react-responsive-redux? I have the same issue about "fakeWidth".

**Comment by modosc** [comment]
@socean2016 the code in `README.md` is exactly what i'm using in production.

**Comment by athenrock** [comment]
I've met this problem, the main thing is that <code>reducers</code> doesn't set it right
```javascript
import {combineReducers} from 'redux'
import userInfo from './userInfo'
import { reducer as responsiveReducer } from 'react-responsive-redux'
const reducers = {
    // ... your other reducers here ...
    userInfo: userInfo,
    responsive: responsiveReducer
}
const rootReducer = combineReducers(reducers)
export default rootReducer
```
This setting should be all right.Now there's a new problem.

![default](https://user-images.githubusercontent.com/11920062/36186725-cd5e4ff4-117b-11e8-8f63-75e4924775ba.png)

Mismatches between server rendering and client rendering，An error has occurred<code><!-- react-empty:</code>

**Comment by modosc** [comment]
> Mismatches between server rendering and client rendering，

 i'm guessing that your browser window doesn't match up with the default size, if it's something more please open a separate issue.

**Comment by SevenZark** [comment]
I am having the same issue. I am not using immutable or next.js. Also it does not seem to matter what width my browser viewport is set at. I am using the exact example code from the Readme for the react-responsive-redux portion of this.

**Comment by modosc** [comment]
@SevenZark can you post a link to some code so i can take a look?

**Comment by SevenZark** [comment]
> @SevenZark can you post a link to some code so i can take a look?

Thanks for offering! It's from a private repo, but I will paste the relevant code here and you can let me know if it shows you enough.

store factory file:
```
import {createStore, combineReducers} from 'redux'
import { reducer as responsiveReducer } from 'react-responsive-redux'

// App
import {
  contactModal,
  menu,
  atHome,
  backButtonHref,
  globalMessage,
  responsive
} from './reducers'

const defaultState = {
  contactModal: {open: false},
  menu: {open: false},
  atHome: false,
  backButtonHref: '/',
  globalMessage: ''
}

const storeFactory = (initialState = defaultState) => {
  return createStore(combineReducers({
    contactModal, 
    menu,
    atHome,
    backButtonHref,
    globalMessage,
    responsiveReducer
  }), initialState)
}

export default storeFactory
```

server startup file:
```
import {renderToString} from 'react-dom/server'
import {onPageLoad} from 'meteor/server-render'
import {Helmet} from 'react-helmet'
import {StaticRouter} from 'react-router'
import {Provider} from 'react-redux'

// App
import Routes from '/imports/startup/server/routes'
import Header from '/imports/templates/components/header/index.jsx'
import storeFactory from '/imports/redux/store-factory'
import ContactForm from '/imports/templates/components/contact-form/index.jsx'

onPageLoad(sink => {

  const store = storeFactory(),
    {dispatch} = store,
    mobileDetect = mobileParser(sink.request)

  dispatch(setMobileDetect(mobileDetect))

  const App = props => {

    return (

      <Provider store={store}>

        <div>

          <Helmet
            defaultTitle="My Site"
            titleTemplate="%s | My Site"
          >
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon.png"/>
            <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
            <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
            <link rel="manifest" href="/site.webmanifest"/>
            <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
            <meta name="msapplication-TileColor" content="#da532c"/>
            <meta name="theme-color" content="#ffffff"/>
          </Helmet>

          <div className="frame">
            <Header/>
          </div>

          <div className="content">
            <StaticRouter location={props.location} context={{}}>
              <Routes location={props.location}/>
            </StaticRouter>
          </div>
        </div>

      </Provider>
    )
  }

  sink.renderIntoElementById('app', renderToString(<App location={sink.request.url}/>))

  const helmet = Helmet.renderStatic()
  sink.appendToHead(helmet.title.toString())
  sink.appendToHead(helmet.meta.toString())
  sink.appendToHead(helmet.link.toString())
})
```

problem component:
```
import React, {Component} from 'react'
import Responsive from 'react-responsive'
import {MobileScreen, DesktopScreen} from 'react-responsive-redux'

// App
import Mobile from './mobile/index.jsx'
import TabletAndWider from './tablet-and-wider/index.jsx'

class Header extends Component {

  render() {
    return (
      <div>
        <MobileScreen>
          <Mobile/>
        </MobileScreen>
        <DesktopScreen>
          <TabletAndWider/>
        </DesktopScreen>
      </div>
    )
  }
}

export default Header
```

**Comment by SevenZark** [comment]
> @SevenZark can you post a link to some code so i can take a look?

Thanks very much for the offer! I pasted some code in a comment, then while looking it over spotted my error, which had to do with how I was accessing the responsiveReducer in my store factory. Apologies for the false positive.

**Comment by modosc** [comment]
i posted up some [example code](https://github.com/modosc/react-responsive-redux/tree/master/example) - please check this out and lmk if there's still an issue.
