### ISSUE TITLE
a question regarding value props in the README

### ISSUE THREAD

**Issue by coolgod** [modosc/react-responsive-redux#5]
```
This example will work fine as long as your browser window is >= 1024px. If it's not you're back to the warning above.
```

why it is ">=1024px", why it isn't ">=992px" ?

**Comment by modosc** [comment]
> why it is ">=1024px", why it isn't ">=992px" ?

because in this case `width: 1024` is what we're telling `react-responsive` our width is on the server side. you are correct in that having a width of `>=992px` will work in this case - i used different numbers here to show the difference between the breakpoints and the `width` value.
