### ISSUE TITLE
Properties in responsive state are not updated

### ISSUE THREAD

**Issue by ataliadvanstep** [modosc/react-responsive-redux#8]
I setup the responsive reducer on my store but it seems props does not reflect the reality. Should I call a dispatch ?

![image](https://user-images.githubusercontent.com/26287180/39046654-ebb81464-4464-11e8-8437-fc779f5333de.png)

**Comment by modosc** [comment]
yes - see the docs or the [example code](https://github.com/modosc/react-responsive-redux/tree/master/example)
